-- Script0026: TRX_ORDER menyimpan ekspedisi yang dipilih pembeli (+ nama snapshot)
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('LOSCONSUMER.TRX_ORDER') AND name = 'COURIER_ID')
BEGIN
    ALTER TABLE LOSCONSUMER.TRX_ORDER ADD COURIER_ID INT NULL;
END;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('LOSCONSUMER.TRX_ORDER') AND name = 'COURIER_NAME')
BEGIN
    ALTER TABLE LOSCONSUMER.TRX_ORDER ADD COURIER_NAME NVARCHAR(100) NULL;
END;