-- Script0017: Role SA + tabel APP_SETTING
-- 1) Buka constraint role agar menerima 'SA'
IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_MASTER_USER_ROLE' AND parent_object_id = OBJECT_ID('LOSCONSUMER.MASTER_USER'))
BEGIN
    ALTER TABLE LOSCONSUMER.MASTER_USER DROP CONSTRAINT CK_MASTER_USER_ROLE;
    ALTER TABLE LOSCONSUMER.MASTER_USER ADD CONSTRAINT CK_MASTER_USER_ROLE CHECK (ROLE IN ('SA', 'OWNER', 'ADMIN'));
END;

-- 2) Seed akun Super Admin (sa / sa123)
IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.MASTER_USER WHERE USERNAME = 'sa')
BEGIN
    INSERT INTO LOSCONSUMER.MASTER_USER (USERNAME, PASSWORD_HASH, DISPLAY_NAME, ROLE, CREATED_BY)
    VALUES (N'sa', N'$2a$11$qLcUxireT/fxTyVcTsRm4OA5.l1xdArA6hGlCvXQJi4hOI.hepdpy', N'Super Admin', 'SA', 'SYSTEM');
END;

-- 3) Tabel pengaturan aplikasi (nilai global; lockout = SA, ongkir/pajak = OWNER/SA)
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'APP_SETTING')
BEGIN
    CREATE TABLE LOSCONSUMER.APP_SETTING (
        ID            INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
        SETTING_KEY   NVARCHAR(100)   NOT NULL UNIQUE,
        SETTING_VALUE NVARCHAR(500)   NOT NULL,
        IS_ACTIVE     BIT             NOT NULL DEFAULT 1,
        CREATED_AT    DATETIME2       NOT NULL DEFAULT GETDATE(),
        CREATED_BY    NVARCHAR(100)   NOT NULL DEFAULT 'SYSTEM',
        UPDATED_AT    DATETIME2       NULL,
        UPDATED_BY    NVARCHAR(100)   NULL,
        VERSION       INT             NOT NULL DEFAULT 1
    );
END;

IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.APP_SETTING WHERE SETTING_KEY = 'LOGIN_FAIL_THRESHOLD')
    INSERT INTO LOSCONSUMER.APP_SETTING (SETTING_KEY, SETTING_VALUE, CREATED_BY)
    VALUES (N'LOGIN_FAIL_THRESHOLD', N'5', N'SYSTEM');

IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.APP_SETTING WHERE SETTING_KEY = 'SHIPPING_FEE')
    INSERT INTO LOSCONSUMER.APP_SETTING (SETTING_KEY, SETTING_VALUE, CREATED_BY)
    VALUES (N'SHIPPING_FEE', N'0', N'SYSTEM');

IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.APP_SETTING WHERE SETTING_KEY = 'TAX_PERCENT')
    INSERT INTO LOSCONSUMER.APP_SETTING (SETTING_KEY, SETTING_VALUE, CREATED_BY)
    VALUES (N'TAX_PERCENT', N'0', N'SYSTEM');