IF EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_PRODUCT')
      AND name = 'PRODUCT_ID'
)
BEGIN
    ALTER TABLE LOSCONSUMER.MASTER_PRODUCT DROP COLUMN PRODUCT_ID;
END;

IF EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_PRODUCT')
      AND name = 'EXTERNAL_ID'
)
BEGIN
    ALTER TABLE LOSCONSUMER.MASTER_PRODUCT DROP COLUMN EXTERNAL_ID;
END;
