-- Script0020: Akun pelanggan + audit trail sisi pelanggan
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'MASTER_CUSTOMER')
BEGIN
    CREATE TABLE LOSCONSUMER.MASTER_CUSTOMER (
        ID            INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
        EMAIL         NVARCHAR(200)   NOT NULL UNIQUE,
        PASSWORD_HASH NVARCHAR(500)   NOT NULL,
        NAME          NVARCHAR(200)   NULL,
        PHONE         NVARCHAR(50)    NULL,
        ADDRESS       NVARCHAR(MAX)   NULL,
        IS_BLOCKED    BIT             NOT NULL DEFAULT 0,
        IS_ACTIVE     BIT             NOT NULL DEFAULT 1,
        CREATED_AT    DATETIME2       NOT NULL DEFAULT GETDATE(),
        CREATED_BY    NVARCHAR(100)   NOT NULL DEFAULT 'SYSTEM',
        UPDATED_AT    DATETIME2       NULL,
        UPDATED_BY    NVARCHAR(100)   NULL,
        VERSION       INT             NOT NULL DEFAULT 1
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'TRX_CUSTOMER_AUDIT_TRAIL')
BEGIN
    CREATE TABLE LOSCONSUMER.TRX_CUSTOMER_AUDIT_TRAIL (
        ID          BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
        CUSTOMER_ID INT             NOT NULL,
        ACTION      NVARCHAR(50)    NOT NULL,
        ACTOR       NVARCHAR(200)   NOT NULL,
        ACTED_AT    DATETIME2       NOT NULL DEFAULT GETDATE(),
        DETAIL      NVARCHAR(MAX)   NULL,
        REASON      NVARCHAR(500)   NULL
    );

    CREATE INDEX IX_TRX_CUSTOMER_AUDIT_TRAIL_CUSTOMER ON LOSCONSUMER.TRX_CUSTOMER_AUDIT_TRAIL (CUSTOMER_ID, ACTED_AT);
END;