IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_USER')
      AND name = 'LOGIN_FAILED_COUNT'
)
BEGIN
    ALTER TABLE LOSCONSUMER.MASTER_USER
        ADD LOGIN_FAILED_COUNT INT  NOT NULL DEFAULT 0,
            IS_BLOCKED         BIT  NOT NULL DEFAULT 0;
END;