IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_PRODUCT')
      AND name = 'DISCOUNT_PERCENT'
)
BEGIN
    ALTER TABLE LOSCONSUMER.MASTER_PRODUCT ADD DISCOUNT_PERCENT INT NULL;
END;