-- =========================================================================
-- Script 0007: Migrasi semua tabel ke Objek SEQUENCE dengan NO CACHE
-- =========================================================================

-- 1. Buat SEQUENCE jika belum ada
IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = 'SEQ_MASTER_PRODUCT' AND schema_id = SCHEMA_ID('LOSCONSUMER'))
BEGIN
    CREATE SEQUENCE LOSCONSUMER.SEQ_MASTER_PRODUCT AS INT START WITH 1 INCREMENT BY 1 NO CACHE;
END;

IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = 'SEQ_REQUEST_PRODUCT' AND schema_id = SCHEMA_ID('LOSCONSUMER'))
BEGIN
    CREATE SEQUENCE LOSCONSUMER.SEQ_REQUEST_PRODUCT AS BIGINT START WITH 1 INCREMENT BY 1 NO CACHE;
END;

IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE name = 'SEQ_RESPONSE_PRODUCT' AND schema_id = SCHEMA_ID('LOSCONSUMER'))
BEGIN
    CREATE SEQUENCE LOSCONSUMER.SEQ_RESPONSE_PRODUCT AS BIGINT START WITH 1 INCREMENT BY 1 NO CACHE;
END;

-- 2. Migrasi REQUEST_PRODUCT jika masih berstatus IDENTITY
IF EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'REQUEST_PRODUCT' AND COLUMNPROPERTY(object_id, 'ID', 'IsIdentity') = 1)
BEGIN
    CREATE TABLE LOSCONSUMER.REQUEST_PRODUCT_NEW (
        ID              BIGINT          NOT NULL PRIMARY KEY DEFAULT (NEXT VALUE FOR LOSCONSUMER.SEQ_REQUEST_PRODUCT),
        TRACE_ID        NVARCHAR(100)   NOT NULL,
        ENDPOINT        NVARCHAR(500)   NOT NULL,
        HTTP_METHOD     NVARCHAR(10)    NOT NULL,
        HEADERS         NVARCHAR(MAX)   NULL,
        QUERY_PARAMS    NVARCHAR(MAX)   NULL,
        BODY            NVARCHAR(MAX)   NULL,
        IP_ADDRESS      NVARCHAR(50)    NULL,
        REQUESTED_AT    DATETIME        NOT NULL DEFAULT GETDATE()
    );

    -- Renumber data eksisting agar rapi dan tidak bolong
    INSERT INTO LOSCONSUMER.REQUEST_PRODUCT_NEW (ID, TRACE_ID, ENDPOINT, HTTP_METHOD, HEADERS, QUERY_PARAMS, BODY, IP_ADDRESS, REQUESTED_AT)
    SELECT ROW_NUMBER() OVER (ORDER BY REQUESTED_AT, ID), TRACE_ID, ENDPOINT, HTTP_METHOD, HEADERS, QUERY_PARAMS, BODY, IP_ADDRESS, REQUESTED_AT
    FROM LOSCONSUMER.REQUEST_PRODUCT;

    DROP TABLE LOSCONSUMER.REQUEST_PRODUCT;
    EXEC sp_rename 'LOSCONSUMER.REQUEST_PRODUCT_NEW', 'REQUEST_PRODUCT';

    -- Sesuaikan sequence berikutnya
    DECLARE @MaxReqId BIGINT = ISNULL((SELECT MAX(ID) FROM LOSCONSUMER.REQUEST_PRODUCT), 0) + 1;
    DECLARE @SqlReq NVARCHAR(MAX) = 'ALTER SEQUENCE LOSCONSUMER.SEQ_REQUEST_PRODUCT RESTART WITH ' + CAST(@MaxReqId AS NVARCHAR(30));
    EXEC sp_executesql @SqlReq;
END;

-- 3. Migrasi RESPONSE_PRODUCT jika masih berstatus IDENTITY
IF EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'RESPONSE_PRODUCT' AND COLUMNPROPERTY(object_id, 'ID', 'IsIdentity') = 1)
BEGIN
    CREATE TABLE LOSCONSUMER.RESPONSE_PRODUCT_NEW (
        ID              BIGINT          NOT NULL PRIMARY KEY DEFAULT (NEXT VALUE FOR LOSCONSUMER.SEQ_RESPONSE_PRODUCT),
        TRACE_ID        NVARCHAR(100)   NOT NULL,
        STATUS_CODE     INT             NOT NULL,
        IS_SUCCESS      BIT             NOT NULL,
        MESSAGE         NVARCHAR(MAX)   NULL,
        RESPONSE_BODY   NVARCHAR(MAX)   NULL,
        ELAPSED_MS      BIGINT          NULL,
        RESPONDED_AT    DATETIME        NOT NULL DEFAULT GETDATE()
    );

    -- Renumber data eksisting agar rapi
    INSERT INTO LOSCONSUMER.RESPONSE_PRODUCT_NEW (ID, TRACE_ID, STATUS_CODE, IS_SUCCESS, MESSAGE, RESPONSE_BODY, ELAPSED_MS, RESPONDED_AT)
    SELECT ROW_NUMBER() OVER (ORDER BY RESPONDED_AT, ID), TRACE_ID, STATUS_CODE, IS_SUCCESS, MESSAGE, RESPONSE_BODY, ELAPSED_MS, RESPONDED_AT
    FROM LOSCONSUMER.RESPONSE_PRODUCT;

    DROP TABLE LOSCONSUMER.RESPONSE_PRODUCT;
    EXEC sp_rename 'LOSCONSUMER.RESPONSE_PRODUCT_NEW', 'RESPONSE_PRODUCT';

    -- Sesuaikan sequence berikutnya
    DECLARE @MaxRespId BIGINT = ISNULL((SELECT MAX(ID) FROM LOSCONSUMER.RESPONSE_PRODUCT), 0) + 1;
    DECLARE @SqlResp NVARCHAR(MAX) = 'ALTER SEQUENCE LOSCONSUMER.SEQ_RESPONSE_PRODUCT RESTART WITH ' + CAST(@MaxRespId AS NVARCHAR(30));
    EXEC sp_executesql @SqlResp;
END;

-- 4. Migrasi MASTER_PRODUCT jika masih berstatus IDENTITY
IF EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'MASTER_PRODUCT' AND COLUMNPROPERTY(object_id, 'ID', 'IsIdentity') = 1)
BEGIN
    CREATE TABLE LOSCONSUMER.MASTER_PRODUCT_NEW (
        ID              INT             NOT NULL PRIMARY KEY DEFAULT (NEXT VALUE FOR LOSCONSUMER.SEQ_MASTER_PRODUCT),
        TITLE           NVARCHAR(500)   NOT NULL,
        PRICE           DECIMAL(18,2)   NOT NULL,
        DESCRIPTION     NVARCHAR(MAX)   NULL,
        CATEGORY        NVARCHAR(200)   NULL,
        IMAGE           NVARCHAR(1000)  NULL,
        RATING_RATE     DECIMAL(5,2)    NULL,
        RATING_COUNT    INT             NULL,
        IS_ACTIVE       BIT             NOT NULL DEFAULT 1,
        CREATED_AT      DATETIME        NOT NULL DEFAULT GETDATE(),
        CREATED_BY      NVARCHAR(100)   NOT NULL DEFAULT 'SYSTEM',
        UPDATED_AT      DATETIME        NULL,
        UPDATED_BY      NVARCHAR(100)   NULL,
        VERSION         INT             NOT NULL DEFAULT 1
    );

    INSERT INTO LOSCONSUMER.MASTER_PRODUCT_NEW (ID, TITLE, PRICE, DESCRIPTION, CATEGORY, IMAGE, RATING_RATE, RATING_COUNT, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, VERSION)
    SELECT ID, TITLE, PRICE, DESCRIPTION, CATEGORY, IMAGE, RATING_RATE, RATING_COUNT, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, VERSION
    FROM LOSCONSUMER.MASTER_PRODUCT;

    DROP TABLE LOSCONSUMER.MASTER_PRODUCT;
    EXEC sp_rename 'LOSCONSUMER.MASTER_PRODUCT_NEW', 'MASTER_PRODUCT';

    -- Sesuaikan sequence berikutnya
    DECLARE @MaxMasterId INT = ISNULL((SELECT MAX(ID) FROM LOSCONSUMER.MASTER_PRODUCT), 0) + 1;
    DECLARE @SqlMaster NVARCHAR(MAX) = 'ALTER SEQUENCE LOSCONSUMER.SEQ_MASTER_PRODUCT RESTART WITH ' + CAST(@MaxMasterId AS NVARCHAR(30));
    EXEC sp_executesql @SqlMaster;
END;
