-- Script0027: Kunci reCAPTCHA untuk Konfirmasi Pesanan (kosong = nonaktif, diisi via PengaturanAplikasi)
IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.APP_SETTING WHERE SETTING_KEY = 'RECAPTCHA_SITE_KEY')
    INSERT INTO LOSCONSUMER.APP_SETTING (SETTING_KEY, SETTING_VALUE, CREATED_BY)
    VALUES (N'RECAPTCHA_SITE_KEY', N'', N'SYSTEM');

IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.APP_SETTING WHERE SETTING_KEY = 'RECAPTCHA_SECRET_KEY')
    INSERT INTO LOSCONSUMER.APP_SETTING (SETTING_KEY, SETTING_VALUE, CREATED_BY)
    VALUES (N'RECAPTCHA_SECRET_KEY', N'', N'SYSTEM');