IF OBJECT_ID('LOSCONSUMER.TRX_DISCOUNT_APPROVAL') IS NULL
BEGIN
    CREATE TABLE LOSCONSUMER.TRX_DISCOUNT_APPROVAL
    (
        ID            INT IDENTITY(1,1) PRIMARY KEY,
        PRODUCT_ID    INT NOT NULL
                      REFERENCES LOSCONSUMER.MASTER_PRODUCT(ID),
        OLD_VALUE     DECIMAL(5,2) NULL,
        NEW_VALUE     DECIMAL(5,2) NULL,
        REQUESTED_BY  NVARCHAR(100) NOT NULL,
        REQUESTED_AT  DATETIME2 NOT NULL DEFAULT GETDATE(),
        STATUS        NVARCHAR(20) NOT NULL DEFAULT 'MENUNGGU',
        DECIDED_AT    DATETIME2 NULL,
        DECIDED_BY    NVARCHAR(100) NULL,
        REASON        NVARCHAR(500) NULL
    );

    CREATE UNIQUE INDEX UX_TRX_DISCOUNT_APPROVAL_ONE_PENDING
        ON LOSCONSUMER.TRX_DISCOUNT_APPROVAL (PRODUCT_ID)
        WHERE STATUS = 'MENUNGGU';
END;