IF NOT EXISTS (SELECT 1 FROM sys.columns
               WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_USER') AND name = 'SECRET_KEY')
BEGIN
    ALTER TABLE LOSCONSUMER.MASTER_USER ADD SECRET_KEY NVARCHAR(64) NULL;
END;

-- Backfill kunci untuk user yang belum punya (32 karakter hex dari GUID)
UPDATE LOSCONSUMER.MASTER_USER
SET SECRET_KEY = LOWER(REPLACE(CONVERT(NVARCHAR(36), NEWID()), '-', ''))
WHERE SECRET_KEY IS NULL OR SECRET_KEY = '';

IF NOT EXISTS (SELECT 1 FROM sys.indexes
               WHERE name = 'UX_MASTER_USER_SECRET_KEY' AND object_id = OBJECT_ID('LOSCONSUMER.MASTER_USER'))
BEGIN
    CREATE UNIQUE INDEX UX_MASTER_USER_SECRET_KEY
        ON LOSCONSUMER.MASTER_USER (SECRET_KEY)
        WHERE SECRET_KEY IS NOT NULL;
END;