-- Script0021: TRX_ORDER + TRX_ORDER_ITEM — pesanan pelanggan + snapshot baris
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'TRX_ORDER')
BEGIN
    CREATE TABLE LOSCONSUMER.TRX_ORDER (
        ID           BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
        CUSTOMER_ID  INT             NOT NULL,
        STATUS       NVARCHAR(20)    NOT NULL DEFAULT 'DIPROSES',
        SUBTOTAL     DECIMAL(18,2)   NOT NULL,
        SHIPPING_FEE DECIMAL(18,2)   NOT NULL DEFAULT 0,
        TAX_AMOUNT   DECIMAL(18,2)   NOT NULL DEFAULT 0,
        TOTAL_AMOUNT DECIMAL(18,2)   NOT NULL,
        SHIP_NAME    NVARCHAR(200)   NULL,
        SHIP_PHONE   NVARCHAR(50)    NULL,
        SHIP_ADDRESS NVARCHAR(MAX)   NULL,
        NOTE         NVARCHAR(500)   NULL,
        DIPROSES_AT  DATETIME2       NOT NULL DEFAULT GETDATE(),
        KIRIM_AT     DATETIME2       NULL,
        KIRIM_BY     NVARCHAR(100)   NULL,
        TERIMA_AT    DATETIME2       NULL,
        TERIMA_BY    NVARCHAR(200)   NULL,
        BATAL_AT     DATETIME2       NULL,
        BATAL_BY     NVARCHAR(200)   NULL,
        BATAL_REASON NVARCHAR(500)   NULL,
        CREATED_AT   DATETIME2       NOT NULL DEFAULT GETDATE(),
        CREATED_BY   NVARCHAR(200)   NOT NULL,
        UPDATED_AT   DATETIME2       NULL,
        UPDATED_BY   NVARCHAR(200)   NULL,
        VERSION      INT             NOT NULL DEFAULT 1
    );

    CREATE INDEX IX_TRX_ORDER_CUSTOMER ON LOSCONSUMER.TRX_ORDER (CUSTOMER_ID, CREATED_AT);
    CREATE INDEX IX_TRX_ORDER_STATUS  ON LOSCONSUMER.TRX_ORDER (STATUS, CREATED_AT);
END;

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'TRX_ORDER_ITEM')
BEGIN
    CREATE TABLE LOSCONSUMER.TRX_ORDER_ITEM (
        ID         BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
        ORDER_ID   BIGINT          NOT NULL,
        PRODUCT_ID INT             NOT NULL,
        TITLE      NVARCHAR(500)   NOT NULL,
        UNIT_PRICE DECIMAL(18,2)   NOT NULL,
        DISCOUNT_PERCENT DECIMAL(5,2) NULL,
        QUANTITY   INT             NOT NULL,
        SUBTOTAL   DECIMAL(18,2)   NOT NULL
    );

    CREATE INDEX IX_TRX_ORDER_ITEM_ORDER ON LOSCONSUMER.TRX_ORDER_ITEM (ORDER_ID);
END;