IF EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_PRODUCT')
      AND name = 'EXTERNAL_ID'
)
BEGIN
    EXEC sp_rename 'LOSCONSUMER.MASTER_PRODUCT.EXTERNAL_ID', 'PRODUCT_ID', 'COLUMN';
END;
