-- Script0022: TRX_CART_ITEM — keranjang server untuk pelanggan yang masuk
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'TRX_CART_ITEM')
BEGIN
    CREATE TABLE LOSCONSUMER.TRX_CART_ITEM (
        ID          BIGINT       NOT NULL IDENTITY(1,1) PRIMARY KEY,
        CUSTOMER_ID INT          NOT NULL,
        PRODUCT_ID  INT          NOT NULL,
        QUANTITY    INT          NOT NULL DEFAULT 1,
        CREATED_AT  DATETIME2    NOT NULL DEFAULT GETDATE(),
        CONSTRAINT UQ_TRX_CART_ITEM_CUSTOMER_PRODUCT UNIQUE (CUSTOMER_ID, PRODUCT_ID)
    );

    CREATE INDEX IX_TRX_CART_ITEM_CUSTOMER ON LOSCONSUMER.TRX_CART_ITEM (CUSTOMER_ID);
END;