-- Script0024: MASTER_COURIER — master ekspedisi (kurir) dengan ongkir per ekspedisi
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'MASTER_COURIER')
BEGIN
    CREATE TABLE LOSCONSUMER.MASTER_COURIER (
        ID           INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
        NAME         NVARCHAR(100)   NOT NULL UNIQUE,
        SHIPPING_FEE DECIMAL(18,2)   NOT NULL DEFAULT 0,
        IS_ACTIVE    BIT             NOT NULL DEFAULT 1,
        CREATED_AT   DATETIME2       NOT NULL DEFAULT GETDATE(),
        CREATED_BY   NVARCHAR(100)   NOT NULL DEFAULT 'SYSTEM',
        UPDATED_AT   DATETIME2       NULL,
        UPDATED_BY   NVARCHAR(100)   NULL,
        VERSION      INT             NOT NULL DEFAULT 1
    );
END;

IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.MASTER_COURIER WHERE NAME = N'Kurir Toko')
    INSERT INTO LOSCONSUMER.MASTER_COURIER (NAME, SHIPPING_FEE, CREATED_BY) VALUES (N'Kurir Toko', 10000, 'SYSTEM');

IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.MASTER_COURIER WHERE NAME = N'J&T')
    INSERT INTO LOSCONSUMER.MASTER_COURIER (NAME, SHIPPING_FEE, CREATED_BY) VALUES (N'J&T', 15000, 'SYSTEM');