-- Script0032: Sesi aktif tunggal - IS_LOGGED (0/1) dan LAST_DEVICE untuk pelanggan & staf
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_CUSTOMER') AND name = 'IS_LOGGED')
    ALTER TABLE LOSCONSUMER.MASTER_CUSTOMER ADD IS_LOGGED BIT NOT NULL DEFAULT 0;
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_CUSTOMER') AND name = 'LAST_DEVICE')
    ALTER TABLE LOSCONSUMER.MASTER_CUSTOMER ADD LAST_DEVICE NVARCHAR(300) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_USER') AND name = 'IS_LOGGED')
    ALTER TABLE LOSCONSUMER.MASTER_USER ADD IS_LOGGED BIT NOT NULL DEFAULT 0;
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_USER') AND name = 'LAST_DEVICE')
    ALTER TABLE LOSCONSUMER.MASTER_USER ADD LAST_DEVICE NVARCHAR(300) NULL;
GO