-- Script0028: ALTCHA self-hosted menggantikan reCAPTCHA (kunci kosong = nonaktif)
IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.APP_SETTING WHERE SETTING_KEY = 'ALTCHA_HMAC_KEY')
    INSERT INTO LOSCONSUMER.APP_SETTING (SETTING_KEY, SETTING_VALUE, CREATED_BY)
    VALUES (N'ALTCHA_HMAC_KEY', N'', N'SYSTEM');

IF EXISTS (SELECT 1 FROM LOSCONSUMER.APP_SETTING WHERE SETTING_KEY IN ('RECAPTCHA_SITE_KEY', 'RECAPTCHA_SECRET_KEY'))
    DELETE FROM LOSCONSUMER.APP_SETTING WHERE SETTING_KEY IN ('RECAPTCHA_SITE_KEY', 'RECAPTCHA_SECRET_KEY');