-- Script0018: TRX_AUDIT_LOG — jejak aksi pengurus (sumber kebenaran lockout)
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'TRX_AUDIT_LOG')
BEGIN
    CREATE TABLE LOSCONSUMER.TRX_AUDIT_LOG (
        ID           BIGINT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
        ENTITY       NVARCHAR(50)    NOT NULL,
        ENTITY_ID    NVARCHAR(50)    NULL,
        ACTION       NVARCHAR(50)    NOT NULL,
        ACTOR        NVARCHAR(100)   NOT NULL,
        ACTED_AT     DATETIME2       NOT NULL DEFAULT GETDATE(),
        OLD_SNAPSHOT NVARCHAR(MAX)   NULL,
        NEW_SNAPSHOT NVARCHAR(MAX)   NULL,
        REASON       NVARCHAR(500)   NULL,
        TRACE_ID     NVARCHAR(100)   NULL
    );

    CREATE INDEX IX_TRX_AUDIT_LOG_ENTITY ON LOSCONSUMER.TRX_AUDIT_LOG (ENTITY, ENTITY_ID, ACTED_AT);
    CREATE INDEX IX_TRX_AUDIT_LOG_ACTOR  ON LOSCONSUMER.TRX_AUDIT_LOG (ACTOR, ACTED_AT);
END;