-- Script0031: Status pesanan dipecah - DIPROSES menjadi MENUNGGU_KONFIRMASI lalu DIKEMAS
DECLARE @df NVARCHAR(200) = (
    SELECT dc.name
    FROM sys.default_constraints dc
    WHERE dc.parent_object_id = OBJECT_ID('LOSCONSUMER.TRX_ORDER')
      AND dc.parent_column_id = COLUMNPROPERTY(OBJECT_ID('LOSCONSUMER.TRX_ORDER'), 'STATUS', 'ColumnId')
);
IF @df IS NOT NULL
    EXEC('ALTER TABLE LOSCONSUMER.TRX_ORDER DROP CONSTRAINT ' + QUOTENAME(@df));
GO

ALTER TABLE LOSCONSUMER.TRX_ORDER
    ADD CONSTRAINT DF_TRX_ORDER_STATUS DEFAULT ('MENUNGGU_KONFIRMASI') FOR STATUS;
GO

UPDATE LOSCONSUMER.TRX_ORDER
SET STATUS = 'MENUNGGU_KONFIRMASI'
WHERE STATUS = 'DIPROSES';
GO