IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_PRODUCT')
      AND name = 'STOCK'
)
BEGIN
    ALTER TABLE LOSCONSUMER.MASTER_PRODUCT ADD STOCK INT NOT NULL DEFAULT 0;
END;