IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE schema_id = SCHEMA_ID('LOSCONSUMER') AND name = 'MASTER_USER')
BEGIN
    CREATE TABLE LOSCONSUMER.MASTER_USER (
        -- Primary Key
        ID              INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,

        -- Business Columns
        USERNAME        NVARCHAR(100)   NOT NULL UNIQUE,
        PASSWORD_HASH   NVARCHAR(500)   NOT NULL,
        DISPLAY_NAME    NVARCHAR(200)   NULL,
        ROLE            NVARCHAR(20)    NOT NULL DEFAULT 'ADMIN'
                        CONSTRAINT CK_MASTER_USER_ROLE CHECK (ROLE IN ('ADMIN', 'OWNER')),
        LAST_LOGIN_AT   DATETIME        NULL,

        -- 6 Kolom Wajib
        IS_ACTIVE       BIT             NOT NULL DEFAULT 1,
        CREATED_AT      DATETIME        NOT NULL DEFAULT GETDATE(),
        CREATED_BY      NVARCHAR(100)   NOT NULL DEFAULT 'SYSTEM',
        UPDATED_AT      DATETIME        NULL,
        UPDATED_BY      NVARCHAR(100)   NULL,
        VERSION         INT             NOT NULL DEFAULT 1   -- Optimistic Concurrency
    );
END;

IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.MASTER_USER WHERE USERNAME = 'admin')
BEGIN
    INSERT INTO LOSCONSUMER.MASTER_USER (USERNAME, PASSWORD_HASH, DISPLAY_NAME, ROLE, CREATED_BY)
    VALUES (N'admin', N'$2a$11$gEQPUWumVw/5dr80tGTM7ebzlF/dDUlU2Dkl7FuWccMak9HEGF.my', N'Administrator', 'ADMIN', 'SYSTEM');
END;

IF NOT EXISTS (SELECT 1 FROM LOSCONSUMER.MASTER_USER WHERE USERNAME = 'owner')
BEGIN
    INSERT INTO LOSCONSUMER.MASTER_USER (USERNAME, PASSWORD_HASH, DISPLAY_NAME, ROLE, CREATED_BY)
    VALUES (N'owner', N'$2a$11$0QCOOOPyEHOhCLSug/6LTOHh/SuqxO22GlIw/7H5uCFV8IV5tpvz2', N'Pemilik Toko', 'OWNER', 'SYSTEM');
END;