-- Script0029: Nomor pesanan (ORDER_NUMBER) - format INV{yyyyMMddHHmmssfff}{urutan 5 digit}
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('LOSCONSUMER.TRX_ORDER') AND name = 'ORDER_NUMBER')
    ALTER TABLE LOSCONSUMER.TRX_ORDER ADD ORDER_NUMBER NVARCHAR(50) NULL;

-- Backfill pesanan lama: tanggal dibuat (server time) + urutan dari ID
UPDATE LOSCONSUMER.TRX_ORDER
SET ORDER_NUMBER = 'INV' + FORMAT(CREATED_AT, 'yyyyMMddHHmmssfff')
                 + RIGHT('00000' + CAST(ID AS VARCHAR(10)), 5)
WHERE ORDER_NUMBER IS NULL;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_TRX_ORDER_ORDER_NUMBER' AND object_id = OBJECT_ID('LOSCONSUMER.TRX_ORDER'))
    CREATE UNIQUE NONCLUSTERED INDEX UX_TRX_ORDER_ORDER_NUMBER ON LOSCONSUMER.TRX_ORDER (ORDER_NUMBER)
    WHERE ORDER_NUMBER IS NOT NULL;