-- Script0019: Lockout kini berbasis TRX_AUDIT_LOG — kolom counter dihapus
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_USER') AND name = 'LOGIN_FAILED_COUNT')
BEGIN
    ALTER TABLE LOSCONSUMER.MASTER_USER DROP COLUMN LOGIN_FAILED_COUNT;
END;