-- Master kategori: kategori produk menjadi entitas master.
IF OBJECT_ID('LOSCONSUMER.MASTER_CATEGORY') IS NULL
BEGIN
    CREATE TABLE LOSCONSUMER.MASTER_CATEGORY
    (
        ID         INT IDENTITY(1,1) PRIMARY KEY,
        NAME       NVARCHAR(100) NOT NULL UNIQUE,
        IS_ACTIVE  BIT           NOT NULL DEFAULT 1,
        CREATED_AT DATETIME2     NOT NULL DEFAULT GETDATE(),
        CREATED_BY NVARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
        UPDATED_AT DATETIME2     NULL,
        UPDATED_BY NVARCHAR(100) NULL,
        VERSION    INT           NOT NULL DEFAULT 1
    );

    -- Migrasi: nama kategori yang sudah dipakai produk menjadi master.
    INSERT INTO LOSCONSUMER.MASTER_CATEGORY (NAME, CREATED_AT, CREATED_BY)
    SELECT DISTINCT CATEGORY, GETDATE(), 'SYSTEM'
    FROM LOSCONSUMER.MASTER_PRODUCT
    WHERE CATEGORY IS NOT NULL AND LTRIM(RTRIM(CATEGORY)) != '';
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('LOSCONSUMER.MASTER_PRODUCT')
      AND name = 'CATEGORY_ID'
)
BEGIN
    ALTER TABLE LOSCONSUMER.MASTER_PRODUCT ADD CATEGORY_ID INT NULL;
END;
GO

-- Backfill: produk kini merujuk master dengan nama yang sama (batch terpisah).
UPDATE P
SET    P.CATEGORY_ID = C.ID
FROM   LOSCONSUMER.MASTER_PRODUCT P
JOIN   LOSCONSUMER.MASTER_CATEGORY C ON C.NAME = P.CATEGORY;